# Generated by Django 2.0.4 on 2018-04-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
